config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/', {to: 'welcome#index', as: 'home'})

  post('/', {to: 'welcome#create'})

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def create
    @amount = params[:amount].to_f
    @tax = params[:tax].to_f
    @tip = params[:tip].to_f
    @people = params[:people].to_f


    @total = (@amount + (@amount * (@tax/100)) + (@tip/100)).to_f / @people

    render 'index'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillSplitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>splitter</h1>
<div>
  <%= form_tag home_path do %>
  <%= label_tag :amount %>
  <%= text_field_tag :amount %>

</div>

<div>

  <%= label_tag :tax %>
  <%= text_field_tag :tax %>

</div>

<div>

  <%= label_tag :tip %>
  <%= text_field_tag :tip %>
</div>

<div>

  <%= label_tag :people %>
  <%= text_field_tag :people %>
</div>

<%= submit_tag 'Submit' %>

<h1>Every person must pay <%= @total %></h1>

<% end %>